### ISSUE TITLE
Typos.

### ISSUE THREAD

**Issue by konkrer** [NodeSchoolSF/how-to-database#1]
Hey Kevin, thanks for the presentation and all the work you put into this repository.

I believe I have found a typo in router.js as I was reading through and looking at some of the code. What I believe the code should be is in the two comments to the right:

    // Wishlists - add a product to a wishlist
    router.post("/wishlists/:id/products", async (req, res) => {
      try {
        if (!req.body.product_id) {
          return res.status(400).json({ error: "missing parameter" });
        }
        const wishlist_id = parseInt(req.params.id, 10);
        const product_id = parseInt(req.params.product_id, 10);   // **req.body.product_id

        const result = await knex("wishlist_products")
          .insert({
            wishlist_id: id,                                      // **wishlist_id: wishlist_id
            product_id: product_id,
          })
          .returning("*");

        return res.status(201).json({ data: result });
      } catch (err) {
        console.error(err);
        return res.status(500).json({ error: "failed to add wishlist product" });
      }
    });

**Comment by kevinsqi** [comment]
Yup, you're totally right - messed those up when I last modified the route. I just fixed them - thanks for catching! 💯
